name: CD
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'build.json'
jobs:
  increment-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out source code
        run: chmod +x .incrementBuild.js
        run: ./incrementBuild.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated version bump on merge to main"
  deploy:
    needs: increment-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Install PM2
        run: npm i -g pm2

      - name: Deploy
        run: pm2 deploy ecosystem.config.js production
        
