name: Linters

on:
  push:
    branches:
      - main
      - "*.x"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run YAML Linter
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
